# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-28 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('belt_app', '0002_auto_20170628_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='quote',
            new_name='content',
        ),
    ]
